server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:

        - id: cliente
          uri: lb://ms-cliente
          predicates:
            - Path=/api/clientes/**

        - id: categoria
          uri: lb://ms-categoria
          predicates:
            - Path=/api/categorias/**

        - id: proveedor
          uri: lb://ms-proveedor
          predicates:
            - Path=/api/proveedores/**

        - id: producto
          uri: lb://ms-producto
          predicates:
            - Path=/api/productos/**

        - id: stock
          uri: lb://ms-stock
          predicates:
            - Path=/api/stock/**

        - id: carrito
          uri: lb://ms-carrito
          predicates:
            - Path=/api/carrito/**

        - id: pedido
          uri: lb://ms-pedido
          predicates:
            - Path=/api/pedidos/**

        - id: pago
          uri: lb://ms-pago
          predicates:
            - Path=/api/pagos/**

        - id: boleta
          uri: lb://ms-boleta
          predicates:
            - Path=/api/boletas/**

        - id: envio
          uri: lb://ms-envio
          predicates:
            - Path=/api/envios/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/